final List productList = [
  "Carnation",
  "Caro",
  "cocoa D'Onofrio",
  "Enviga",
  "Libby's",
  "Juicy Juice",
  "Milo",
  "Nescau",
  "Nesquik",
  "Nestea",
  "Ovaltine",
  "Ricacao",
  "Romanette",
  "Special.T",
  "Supligen",
  "Sweet Leaf Tea",
  "Blue Bottle Coffee Company",
  "Bonka",
  "Buondi",
  "Chameleon Cold-Brew",
  "Christina",
  "Dolca",
  "Dolce Gusto",
  "Ecco",
  "El Chaná",
  "International Roast",
  "Kirma",
  "Loumidis",
  "Mountain Blend",
  "Nescafé",
  "Nespresso",
  "Partner's Blend",
  "Ricoffy",
  "Ricoré",
  "Ristretto",
  "Sical",
  "Sunrise",
  "Taster's Choice ",
  "Tofa ",
  "Zoégas",
  "Water",
  "Aberfoyle",
  "Acqua Panna",
  "Alaçam",
  "Aqua Mineral",
  "Aqua Pod",
  "Aqua Spring ",
  "Aquarel",
  "Arctic",
  "Arrowhead",
  "Baraka",
  "Buxton",
  "Calistoga",
  "Charmoise",
  "Ciego Montero",
  "Contrex",
  "Cristalp",
  "Da Shan YunNan Spring",
  "Dar Natury",
  "Deep Spring",
  "Deer Park",
  "Eco de los Andes",
  "Erikli",
  "Frische Brise",
  "Gerber",
  "Ghadeer",
  "Glaciar",
  "Henniez",
  "Hépar",
  "Hidden Spring",
  "Ice Mountain",
  "Κorpi",
  "La Vie",
  "Levissima",
  "Los Portales",
  "Minéré",
  "Montclair",
  "Nałęczowianka",
  "Nestle Selda",
  "Nestle Vera",
  "Neuselters",
  "Ozarka",
  "Pejo",
  "Perrier",
  "Petrópolis",
  "Plancoët",
  "Poland Spring",
  "Porvenir",
  "Powwow",
  "Princes Gate",
  "Pure Life/Pureza Vital/Vie Pure",
  "Quézac",
  "Recoaro",
  "Saint-Lambert",
  "Sainte-Alix",
  "San Pellegrino",
  "Santa Bárbara",
  "Santa Maria",
  "São Lourenço",
  "Sohat",
  "Springs",
  "Theodora",
  "Valvert",
  "Viladrau",
  "Vittel",
  "Water Line",
  "Waterman",
  "Zephyrhills",
  "Cerevita",
  "Cerelac",
  "Cheerios",
  "Chocapic",
  "Cini Minis",
  "Clusters",
  "Cookie Crisp",
  "Crunch",
  "Curiously Cinnamon",
  "Curiously Strawberry",
  "Estrelitas",
  "Fitness",
  "Force Flakes",
  "Gold Flakes ",
  "Golden Grahams",
  "Golden Morn",
  "Golden Nuggets",
  "Honey Stars",
  "Koko Krunch",
  "Lion Cereal",
  "Milo cereals",
  "Nescau Cereal",
  "Nesquik Breakfast Cereal",
  "Nestle Corn Flakes",
  "Shredded Wheat",
  "Shreddies",
  "TRIO Cereal",
  "Chamyto",
  "Chambinho",
  "Chandelle",
  "Chiquitín",
  "Club",
  "Hirz",
  "La Laitière",
  "La Lechera",
  "LC1",
  "Le Viennois",
  "Moça",
  "Molico",
  "Munch Bunch",
  "Nestle",
  "Nesvita",
  "Ninho",
  "Ski",
  "Sollys",
  "Sveltesse",
  "Svelty",
  "Yoco",
  "Abuelita",
  "Aero",
  "After Eight",
  "All Stars",
  "Allen's",
  "Alpia",
  "Alpino",
  "Animal Bar",
  "Bertie Beetle",
  "Besos de Moza",
  "Big Turk",
  "Blue Riband",
  "Boci",
  "Bono",
  "Bon Pari",
  "Breakaway",
  "Cailler",
  "Capri",
  "Caramac",
  "Carlos V",
  "Charge",
  "Chips Ahoy!",
  "Choclait Chips",
  "Choco Crossies",
  "Chocolate Surpresa",
  "Chokito",
  "Cocosette",
  "Coffee Crisp",
  "D'Onofrio",
  "Damak",
  "Drifter",
  "Fizzfindle",
  "Frigor",
  "Galak/Milkybar",
  "Heaven",
  "Hercules Bars",
  "Joe",
  "Joff",
  "JOJO",
  "Kit Kat",
  "Lion",
  "Lollo",
  "Matchmakers",
  "Milky Bar",
  "Mio",
  "Minties",
  "Mirage",
  "Moça",
  "Munch",
  "Munchies",
  "Negresco",
  "Negrita",
  "Nestle Aero",
  "Nestle Alpine White",
  "Nestle Candy Shop",
  "Nestle Classic",
  "Nestle Dessert",
  "Nestle Milk Chocolate",
  "Nestle Princessa",
  "Nestle with Almonds",
  "Nestle Wonder Ball",
  "Nestle Yes",
  "Orion",
  "Passatempo",
  "Peppermint Crisp",
  "Perugina Baci",
  "Polo",
  "Prestígio",
  "Princessa",
  "Quality Street",
  "Rolo",
  "Rowntrees",
  "Fruit Gums",
  "Fruit Pastilles",
  "Jelly Tots",
  "Juicy Jellies",
  "Pick & Mix",
  "Randoms",
  "Tooty Frooties",
  "Sahne Nuss",
  "Scorched Almonds",
  "Sensação",
  "Smarties",
  "Suflair",
  "Sublime",
  "Sundy",
  "Super 8",
  "Susy",
  "Svitoch",
  "Szerencsi",
  "Tango",
  "Tango Mini Galletas",
  "Texan Bar",
  "Toffee Crisp",
  "Nestle Toll House",
  "Trencito",
  "Triangulo",
  "Turtles",
  "Walnut Whip",
  "Wonka confectionery brands",
  "Bottle Caps",
  "Donutz",
  "Fizzy Jerks",
  "FruiTart Chews",
  "Fun Dip",
  "Gobstoppers",
  "Laffy Taffy",
  "Lik-M-Aid",
  "Nerds",
  "Nerds Gumballs",
  "Nerds Rope",
  "Oompas",
  "Pixy Stix",
  "Rainbow Nerds",
  "Runts",
  "SweeTarts",
  "SweeTarts Rope",
  "SweeTarts Shockers",
  "Tart 'n' Tinys",
  "Thrills",
  "Wonka Bars",
  "Wonka Xploders",
  "XXX mints",
  "Yorkie",
  "Chef-Mate",
  "Davigel",
  "Minor's",
  "Santa Rica",
  "Buitoni",
  "California Pizza Kitchen",
  "Delissio Pizza",
  "DiGiorno Pizza",
  "Hot Pockets",
  "Jack's Pizza",
  "Lean Cuisine",
  "Lean Pockets",
  "Papa Giuseppe",
  "Stouffer's",
  "Sweet Earth Foods",
  "Tombstone Pizza",
  "Wagner Pizza",
  "Frozen Dessert",
  "Åhusglass",
  "Aino",
  "Camy",
  "D'Onofrio",
  "Делта",
  "Δέλτα",
  "Nestle Dibs",
  "Dreyer's",
  "Drumstick",
  "Eskimo",
  "Frigor",
  "Frisco",
  "Froneri",
  "Häagen-Dazs",
  "Hjem-IS",
  "Kimo",
  "Kimy",
  "Kotijäätelö",
  "Maxibon",
  "Mat Kool",
  "Mivvi",
  "Motta",
  "Mövenpick",
  "Nestle Drumstick",
  "Nestle Ice Cream",
  "Nestle Princessa",
  "Oreo Frozen Dessert Sandwiches",
  "Outshine",
  "Pingviini",
  "Push-Up",
  "Real Dairy",
  "Savory",
  "Schöller",
  "Skinny Cow",
  "Sorbetes",
  "Temptations",
  "Underground is",
  "zer0% Fat",
  "Boost",
  "Carnation Instant Breakfast",
  "Compleat",
  "Crucial",
  "Diabetisource",
  "Fibersource",
  "Garden of Life",
  "Glytrol",
  "Impact",
  "Isosource",
  "Meritene",
  "Modulen",
  "Novasource Renal",
  "Nutren",
  "Optifast",
  "Optifibre",
  "Peptamen",
  "Resorb",
  "Resource",
  "Sustagen",
  "Alfare",
  "Beba",
  "Bona",
  "Cerelac",
  "Farinha Láctea",
  "FM 85",
  "Gerber",
  "Good Start",
  "Guigoz",
  "Lactogen",
  "Nan",
  "NAN HA",
  "NanSoy",
  "NaturNes",
  "Neslac",
  "Nestle",
  "Nestle Bear Brand",
  "Nestogen",
  "Nestum",
  "Nido",
  "Piltti",
  "PreNan",
  "SMA",
  "Wyeth",
  "Neston",
  "Nesvita",
  "Pria",
  "Supligen",
  "Petcare",
  "Bakers",
  "Beta",
  "Bonio",
  "Bonnie",
  "Castor & Pollux",
  "Chef Michael's Canine Creations",
  "Felix",
  "Fido",
  "Go Cat",
  "Gourmet",
  "Lily's Kitchen",
  "Lucky Dog",
  "Merrick",
  "Mon Petit",
  "PetLife",
  "Purina",
  "Supercoat",
  "Tails .com",
  "Tidy Cats",
  "Totalcare",
  "Whole Earth Farms",
  "Winalot",
  "Alpo",
  "Purina Beggin’ Strips",
  "Busy Bone",
  "Beneful",
  "Cat Chow",
  "Dog Chow",
  "Fancy Feast",
  "Friskies",
  "Mighty Dog",
  "Purina",
  "Purina ONE",
  "Purina Pro Plan",
  "Buitoni",
  "Herta",
  "Katie's Pizza",
  "Toll House",
  "Carpathia",
  "CHEF",
  "Haoji",
  "Maggi",
  "Thomy",
  "Totole",
  "Winiary",
  "Carnation",
  "Coffee-Mate",
  "Milo",
  "Nestle Omega Plus",
  "Tendre Noix",
  "Acti-V",
  "ActiPlus",
  "Fruit Selection Yogurt",
  "Hirz",
  "Longa Vida",
  "Molico",
  "Munch Bunch ",
  "Nestle Raita",
  "Rawaytee Maza",
  "Ski",
  "Sweet N Tasty Yogurt",
  "Yelly"
];
